name: "ads opctl"

on:
  workflow_dispatch

jobs:
  test:
    name: build publish conda pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: ./.github/workflows/set-dummy-conf
        name: dummy config setup

      - name: install ads opctl
        run: |
          pip install oracle-ads[opctl]
          ads opctl conda --help

      - name: build job-local image
        run: |
          ads opctl build-image -d job-local
          docker images

      - name: build conda pack
        run: |
          cat <<EOF > liuda-environment.yaml
          channels:
            - defaults
            - conda-forge
          dependencies:
            - main::scikit-learn
            - main::pip
            - pip:
              - oracle-ads[geo,notebook,text]
          EOF
          ads opctl conda create -n liuda-test-pack -f liuda-environment.yaml

      - name: publish conda pack
        run: |
          ads opctl conda publish -d -o -p oci://liuda-bucket-test-upload@ociodscdev/conda_environments/cpu/my_simple_env_v1 -s liuda-test-pack_v1
