name: "ads opctl"

on:
  workflow_dispatch

jobs:
  test:
    name: build publish conda pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install ads opctl
        run: |
          pip install oracle-ads[opctl]
          ads opctl conda --help

      - name: build job-local image
        run: |
          ads opctl build-image -d job-local
